spring.application.name=auramarket-backend
server.port=8080

spring.mongodb.uri=mongodb+srv://auramarket_admin:auramarket123@auramarketcluster.kpgskji.mongodb.net/auramarket?retryWrites=true&w=majority&appName=AuraMarketCluster